name: CI

on:
  push:
    branches: [ "chocolate" ]
  pull_request:
    branches: [ "chocolate" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: goto-bus-stop/setup-zig@v2
    - name: system dependencies
      run: sudo apt-get install -y libsdl2-dev libsdl2-mixer-dev libsdl2-net-dev libfluidsynth-dev libsamplerate-dev libpng-dev
    - name: build
      run: zig build --verbose
